---
- name: Include the mime types
  include_vars: mime-types.yml

- name:     Create the main nginx files
  template: src="{{ item.src }}"
            dest="{{ item.dest }}"
            group="{{ ngx_group }}"
            owner="{{ ngx_user }}"
            mode="{{ ngx_config_file_mode | default('0644') }}"
  sudo:     yes
  with_items:
    - { src: 'nginx.conf.j2', dest: "{{ ngx_conf }}" }
    - { src: 'http.conf.j2', dest: "{{ ngx_http_conf }}" }


- name:     Create the main nginx files
  template: src="{{ item.src }}"
            dest="{{ item.dest }}"
            group="{{ ngx_group }}"
            owner="{{ ngx_user }}"
            mode="{{ ngx_config_file_mode | default('0644') }}"
  sudo:     yes
  with_items:
    - { src: 'conf.d/mime.types.j2', dest: "{{ ngx_http_mime_types_conf }}" }
    - { src: 'conf.d/gzip.conf.j2', dest: "{{ ngx_http_gzip_conf_conf }}" }
    - { src: 'conf.d/open_file_cache.conf.j2', dest: "{{ ngx_http_open_file_cache_conf }}" }
    - { src: 'conf.d/logs.conf.j2', dest: "{{ ngx_http_log_conf }}" }
    - { src: 'conf.d/sendfile.conf.j2', dest: "{{ ngx_http_sendfile_conf }}" }
    - { src: 'conf.d/client.conf.j2', dest: "{{ ngx_http_client_conf }}" }
    - { src: 'conf.d/misc.conf.j2', dest: "{{ ngx_http_misc_conf }}" }
    - { src: 'conf.d/headers.conf.j2', dest: "{{ ngx_http_headers_conf }}" }
