---
- name:     Create the main nginx files
  template: src="{{ item.src }}"
            dest="{{ item.dest }}"
            group="{{ ngx_group }}"
            owner="{{ ngx_user }}"
            mode="{{ ngx_config_file_mode | default('0644') }}"
  sudo:     yes
  with_items:
    - { src: 'conf.d/real-ip.conf.j2', dest: "{{ ngx_http_realip_conf }}" }
